### ISSUE TITLE
Existing App Install

### ISSUE THREAD

**Issue by ImTheDeveloper** [trinisofttechnologies/countly-sdk-react-native#1]
Hi I'm looking to integrate the count.ly SDK into my existing react-native app.

I've followed the instructions given on the count.ly website and in this repo README but it appears this is a full new project example. This caused a lot of conflicts with my existing files e.g. package.json etc

Would you be able to advise on the elements I need to download/use in order to integrate with my existing project?

**Comment by trinisofttechnologies** [comment]
Hi, the example project is removed.

Please take a look again.

The example project is moved to another repo.

On 29-Jan-2017 6:19 PM, "MrMobberley" <notifications@github.com> wrote:

Hi I'm looking to integrate the count.ly SDK into my existing react-native
app.

I've followed the instructions given on the count.ly website and in this
repo README but it appears this is a full new project example. This caused
a lot of conflicts with my existing files e.g. package.json etc

Would you be able to advise on the elements I need to download/use in order
to integrate with my existing project?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/trinisofttechnologies/countly-sdk-react-native/issues/1>,
or mute the thread

**Comment by ImTheDeveloper** [comment]
Thanks

I assume I should use this repo  and not the one in the readme?

npm install https://github.com/Countly/countly-sdk-react-native.git

should be

npm install https://github.com/trinisofttechnologies/countly-sdk-react-native.git

**Comment by trinisofttechnologies** [comment]
Yes, this one is still in development.

Only android is complete.

iOS is in progress.

But I sync both the projects on regular interval.

Thanks
